Repository geoadmin/service-search-sphinx, pull requests merged in 2022-06, with the labels that each got.

#495 BGDIINF_SB-2388: remove deprecated layers
  conf/stopo.conf.part
Labels: feature

#496 BGDIINF_SB-2331: add tlm objektklasse to return payload
  conf/search.conf.part
Labels: feature

#497 Update develop docker
  conf/search.conf.part
  conf/stopo.conf.part
  conf/uvek.conf.part
Labels: new-release

#500 clean-up Makefile targets
  Makefile
  README.md
Labels: bug

#499 BGDIDIC-697: Add com_name
  conf/stopo.conf.part
Labels: feature

#502 BGDIDIC-1265: move fida data from kogis_master to stopo_master
  conf/kogis.conf.part
  conf/stopo.conf.part
Labels: feature
