Repository geoadmin/service-search-sphinx, pull requests merged in 2022-05, with the labels that each got.

#487 Add ch.swisstopo.geologie-geologischer_atlas_profile
  conf/stopo.conf.part
Labels: data-integration

#488 Data bgdidid 1457 obstacles
  conf/uvek.conf.part
Labels: data-integration

#489 BGDIDIC-2352: not naming views shop anymore
  conf/stopo.conf.part
Labels: feature

#479 Rework ch.swisstopo.amtliches-strassenverzeichnis
  conf/stopo.conf.part
Labels: feature

#481 Deshopify ch.swisstopo.geologie-geologischer_atlas[*].metadata
  conf/stopo.conf.part
Labels: data-integration

#483 Deshopify ch.swisstopo.geologie-spezialkarten_schweiz[*].metadata
  conf/stopo.conf.part
Labels: data-integration

#490 BGDIDID-1457: update index bazl.luftfahrthindernis
  conf/uvek.conf.part
Labels: data-integration

#491 New Release 2022-05-18-rc1
  conf/stopo.conf.part
  conf/uvek.conf.part
Labels: new-release

#492 Fix column name
  conf/stopo.conf.part
Labels: bug

#494 Fix uvek notruf
  conf/uvek.conf.part
Labels: bug

#493 final shop clean-up
  conf/stopo.conf.part
Labels: feature
