Repository geoadmin/service-search-sphinx, pull requests merged in 2022-08, with the labels that each got.

#501 pull silently
  Makefile
  scripts/pg2sphinx.sh
Labels: feature

#508 Maque the dockerization productive - Migration Frankfurt
  .gitignore
  .isort.cfg
  .pylintrc
  .style.yapf
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  buildspec.yml
  conf/00_db.conf.part
  conf/bafu.conf.part
  conf/bod.conf.part
  conf/dritte.conf.part
  conf/edi.conf.part
  conf/evd.conf.part
  conf/kogis.conf.part
  conf/lubis.conf.part
  conf/search.conf.part
  conf/stopo.conf.part
  conf/uvek.conf.part
  conf/vbs.conf.part
  deploy/README
  deploy/deploy-conf-only.sh
  deploy/deploy.cfg
  deploy/hooks_conf_only/post-restore
  deploy/hooks_conf_only/post-restore-code
  deploy/move-template.sh
  dev.env
  int.env
  prod.env
  scripts/check-config-local.sh
  scripts/docker-cmd.sh
  scripts/docker-crontab
  scripts/docker-entry.sh
  scripts/index-sync-rotate.sh
  scripts/pg2sphinx.sh
  scripts/pg2sphinx_trigger.py
  scripts/pre-commit.sh
  test/sphinxapi.py
  test/test.py
Labels: new-release

#509 remove warning on docker login
  Makefile
Labels: bug

#510 remove warning on docker login
  Makefile
Labels: bug

#511 BGDIINF_SB-2549: improve stability of index sync and rotation
  Dockerfile
  scripts/index-sync-rotate.sh
Labels: bug

#512 BGDIINF_SB-2549:a few major changes in the rsync process
  Dockerfile
  scripts/index-sync-rotate.sh
Labels: bug
