Repository geoadmin/service-search-sphinx, pull requests merged in 2022-11, with the labels that each got.

#542 BGDIDIC-2523: add new layer ch.bazl.luftfahrthindernis-klein
  conf/uvek.conf.part
Labels: data-integration

#544 BGDIDIC-2532: add ch.bak.halteplaetze-jenische_sinti_roma
  conf/bak.conf.part
Labels: feature

#543 BGDIDIC-2472: update zone index
  conf/uvek.conf.part
Labels: feature

#545 BGDIDIC-2494: add ch_bafu_gewaesser_uferbestockung
  conf/bafu.conf.part
Labels: feature

#546 fix wrong index configuration
  conf/bak.conf.part
Labels: bug
