Repository geoadmin/service-search-sphinx, pull requests merged in 2022-09, with the labels that each got.

#514 BGDIINF_SB-2530: service sphinxsearch liveness probe
  Dockerfile
  scripts/checker.sh
Labels: feature

#513 Update index-sync-rotate.sh
  scripts/index-sync-rotate.sh
Labels: bug

#516 BGDIINF_SB-2353: Fixing CI manual build
  buildspec.yml
Labels: bug

#517 Fix update liveness probe
  Dockerfile
  scripts/checker.sh
Labels: bug

#504 BGDIDIC-1792: add nummer to index
  conf/stopo.conf.part
Labels: feature

#515 Feature patch develop
  scripts/index-sync-rotate.sh
Labels: feature, new-release

#506 BGDIDIC-2472: Add zone_name_de
  conf/uvek.conf.part
Labels: feature

#518 BGDIINF_SB-2332: rename objektlasse attribute into objectclass
  conf/search.conf.part
Labels: feature

#520 Patch develop
  buildspec.yml
Labels: new-release

#519 New Release 2022-09-07-rc1
  conf/search.conf.part
  conf/stopo.conf.part
  conf/uvek.conf.part
Labels: new-release

#521 fix docker-cmd script, do not create index on container start which are
  scripts/docker-cmd.sh
Labels: bug

#522 fix docker-cmd script, do not create index on container start which are
  scripts/docker-cmd.sh
Labels: bug

#523 fix query
  conf/search.conf.part
Labels: bug

#525 BGDIINF_SB-2530: add a first draft of readiness probe
  scripts/checker.sh
  scripts/docker-cmd.sh
  scripts/docker-entry.sh
Labels: feature

#527 fix table scan behaviour
  scripts/pg2sphinx_trigger.py
Labels: bug

#530 BGDIINF_SB-2587: improvements in stability
  scripts/index-sync-rotate.sh
Labels: bug

#531 BGDIINF_SB-2587: patch branch
  scripts/index-sync-rotate.sh
Labels: bug

#534 BGDIINF_SB-2562: make the logs searchd.log and query.log visible
  Dockerfile
  scripts/docker-cmd.sh
  scripts/docker-crontab
  scripts/index-sync-rotate.sh
Labels: feature

#537 Fix address rotation issue
  scripts/index-sync-rotate.sh
  scripts/pg2sphinx_trigger.py
Labels: bug

#533 run container as non root user geodata
  Dockerfile
  scripts/checker.sh
  scripts/docker-cmd.sh
  scripts/docker-entry.sh
Labels: feature
