Repository geoadmin/service-search-sphinx, pull requests merged in 2023-12, with the labels that each got.

#586 BGDIDIC-2709 add search config for:
  conf/uvek.conf.part
Labels: data-integration

#587 New Release 2023-12-20-rc1
  conf/dritte.conf.part
  conf/stopo.conf.part
  conf/uvek.conf.part
Labels: new-release

#588 this will fix an issue that has ocurred during the initial start of the
  scripts/docker-cmd.sh
  scripts/pg2sphinx.sh
Labels: bug

#590 Fixing index with time
  conf/stopo.conf.part
Labels: bug

#595 fix/suppress warnings during the scan of the efs with find
  scripts/pg2sphinx.sh
Labels: bug
