Repository geoadmin/service-search-sphinx, pull requests merged in 2023-05, with the labels that each got.

#568 BGDIDIC-2583: add from/to node uuid
  conf/stopo.conf.part
Labels: feature

#562 BGDIDIC-1783: add columns to detail index
  conf/stopo.conf.part
Labels: feature

#569 New Release 2023-05-10-rc1
  conf/search.conf.part
  conf/stopo.conf.part
  conf/wordforms_main.txt
Labels: new-release

#570 using correct origin naming for haltestellen index
  conf/search.conf.part
Labels: bug
