Repository geoadmin/service-search-sphinx, pull requests merged in 2024-09, with the labels that each got.

#630 PB-201: Updated CI name for milestone branch protection
  .github/workflows/create-milestone.yml
Labels: feature

#631 BGDIDIC-2865: Notfalltreffpunkte
  conf/vbs.conf.part
Labels: data-integration

#632 BGDIDIC-2865: fix Notfalltreffpunkte
  conf/vbs.conf.part
Labels: bug

#634 BGDIDIC-2865: id does id has to be an int?
  conf/vbs.conf.part
Labels: bug
