Repository geoadmin/service-search-sphinx, pull requests merged in 2024-05, with the labels that each got.

#616 New Release 2024-05-15-rc1
  conf/edi.conf.part
  conf/search.conf.part
Labels: new-release

#617 PB-428: Updated json logging format
  scripts/index-sync-rotate.sh
Labels: feature

#618 PB-428: Updated json loggin format
  scripts/index-sync-rotate.sh
Labels: feature

#619 BGDIDIC-2829: add index for geologie hartsteinabbau
  conf/stopo.conf.part
Labels: data-integration
