Repository geoadmin/service-search-sphinx, pull requests merged in 2024-01, with the labels that each got.

#594 swissboundaries3d-gemeinden: Even though there are going to be created a large index, this pr will
  conf/stopo.conf.part
Labels: feature

#597 PB-82: prepare migration to k8s
  Dockerfile
  scripts/docker-cmd.sh
  scripts/docker-crontab
  scripts/index-sync-rotate.sh
Labels: feature

#598 New Release 2024-01-31-rc1
  Dockerfile
  conf/stopo.conf.part
  scripts/docker-cmd.sh
  scripts/docker-crontab
  scripts/index-sync-rotate.sh
Labels: new-release

#599 fix uvek.conf.part
  conf/uvek.conf.part
Labels: bug
